### ISSUE TITLE
Is there a way to change the locale?

### ISSUE THREAD

**Issue by Skeeve** [kixam/TW5-datePicker#10]
I'd like to use german locale to get german month and day names.

momentum.js seems to support this. Is it possible in this plugin?

**Comment by kixam** [comment]
Hello @Skeeve 

This plugin will use the same locale as the TiddlyWiki, so if you change the language of your TW to German, the month and day names in the date pickers will immediately turn to German.

**Comment by Skeeve** [comment]
Could you please make it so that the LOCALE can be changed? I'm simply asking because I usually use the English locale for my tools but still need the german locale for this matter.
