### ISSUE TITLE
Locale not used

### ISSUE THREAD

**Issue by Skeeve** [kixam/TW5-datePicker#11]
In #10 you told me that your plugin uses the browser's locale.

Please see attached screenshot.

Using Safari with German locale (see the menu appearing in German) I still get US dates.

<img width="502" alt="image" src="https://user-images.githubusercontent.com/725404/67180216-3ab67680-f3d9-11e9-9b72-f49ffbf37a4a.png">

**Comment by Skeeve** [comment]
Seems I found what I can do…

Create a tiddler `$:/language` with content

```
$:/languages/de
```

**Comment by kixam** [comment]
hello @Skeeve , I did not say the plugin would use the browser locale, I said it would use the TiddlyWiki locale, that is, a locale plugin that you install and activate within your TiddlyWiki, using the settings tiddler, aka `$:/ControlPanel`

overloading the `$:/language` tiddler might also do the trick, but I would rather recommend using a so-called language plugin from the official library
