### ISSUE TITLE
UTC conversion

### ISSUE THREAD

**Issue by agrudzinsky** [kixam/TW5-datePicker#6]
I'm trying to use your plugin to implement a task management system in TW5.  I created a date field "scheduled" and I am trying to set it using your plugin.  The problem is that TW5 stores dates in UTC, and your plugin chops off the time altogether setting the time to "YYYYMMDD000000000". This is interpreted as UTC by TW5. It turns out 7 hours behind the correct date time (I live in US Pacific zone).  Try it in your own  example.  When you set {{!!create}} using <$edit-date/>, it is read back by TimezoneOffset hours behind the current date.

To fix this, I had to change your "$:/plugins/kixam/datepicker/widget.datepicker.js" tiddler adding changing moment() to moment.utc():

`DatePickerWidget.prototype.refreshSelf = function() {
    var val = moment.utc(this.getEditInfo().value, this.saveFormat);
    if(val.isValid()) {
      this.editor.value = val.format(this.editFormat);
      this.picker.setMoment(val, true);
    }
  }`

This makes the widget to convert the date from UTC when reading.

The problem is that pickadate.js toString() method still returns the date without time.  I had to use getMoment() instead of toString() and then generate the field value from the moment object:

`  DatePickerWidget.prototype.onPickerDateSelect = function() {

var val=this.picker.getMoment()
val.utc();
var fieldValue = val.format(this.saveFormat);
    this.saveChanges(fieldValue);
$tw.rootWidget.dispatchEvent({type: "tm-auto-save-wiki"});
  };
`

I also added the auto-save command after saveChanges() to autosave the TW file.

I also need the ability to set the time, at least, by typing it into the text field.  Currently, the time portion seems to be chopped off during the saving.

**Comment by kixam** [comment]
Hello @agrudzinsky ,

thank you for your inputs.

As stated in the [documentation on the demo site](http://kixam.github.io/TW5-datePicker/#Usage), this plugin does not manage time at all. It is not offering to pick time so it ignores the time part of timestamps altogether.

This is due to a known and wanted limitation of the [backend JS library](https://github.com/dbushell/Pikaday). I have been thinking of using a [fork](https://github.com/owenmead/Pikaday) instead, but was worried it would not get the updates from vanilla. But it seems there is recent activity on the repository, so maybe if someone needs time picking it is a good opportunity to switch over.

I will look into it ASAP.

By the way, I really appreciate your code samples and testing. Next time, if you feel like it, do not hesitate to issue a pull request.

**Comment by agrudzinsky** [comment]
Thanks for your reply.  I understand that the plugin is not supposed to handle time at all.  But the way it works, it really does handle time.  It sets the time to 00:00:00.000 and since TW5 interprets this as UTC, the date turns out to be wrong as well.  For me, when I set the date to today, "2016-03-17", the time field is set to "20160317000000000 UTC" and is read back as "2016-03-16 17:00 PDT".  If I simply chop off the time part, I get the wrong date.

If I lived, say, in Paris, the time would be set to "2016-03-17 01:00:00.000" so, at least, the date part would be correct if you simply chop off the time.  But to the unfortunate folks living west from Greenwich, chopping off the time leaves you with a wrong date (the day before from what was set).

The only way to handle this, as I see it, is to convert time to UTC when saving the field and from UTC to local time when reading it.

I really wish Jeremy Ruston would use local time in TW5.  He lives in Oxford and for him, there is no difference, but for the rest of us, it seems to cause a lot of trouble.

**Comment by kixam** [comment]
I see, so it really is about a bug

Anyway, while I am at it, I might as well kill two birds with one stone. It will be all the clearer.

**Comment by agrudzinsky** [comment]
Yes, it does seem to be a bug, even if I don't use the time portion.  I set the date to "2016-03-17", then read it back using <$view format="date" template="YYYY-MM-DD"/>, and it returns "2016-03-16".  Thanks!  I really appreciate your attention.  I fixed it for myself, but I thought it would be helpful to fix it for everyone.
