### ISSUE TITLE
Add a "now" option to the picker

### ISSUE THREAD

**Issue by diego898** [kixam/TW5-datePicker#8]
Is there any way to add a "now" button which will automatically select today's date **and time** and close the picker?

**Comment by kixam** [comment]
hello @diego898 
this would have to be implemented in the [underlying tool](https://github.com/owenmead/Pikaday) but actually you do not really need it. You can easily implement a TW button that sets the value of your field to `now` instead, for instance:

```
<$button>
<$action-setfield $field=myfield $value=<<now "YYYY-0MM-0DD hh:0mm:0ss">>/>
Now
</$button>
```
